### ISSUE TITLE
AWS Cloudwatch adapter crashes

### ISSUE THREAD

**Issue by getsoubl** [awslabs/k8s-cloudwatch-adapter#85]
k8s-cloudwatch-adapter pod is not able to start in EC2 environment. Running kubectl logs k8s-cloudwatch-adapter-pod -n custom-metrics I get the following error

I0518 05:57:06.736713 1 controller.go:35] Setting up external metric event handlers I0518 05:57:06.736816 1 controller.go:57] initializing controller panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]: github.com/awslabs/k8s-cloudwatch-adapter/pkg/aws.GetLocalRegion(0x0, 0x0) /go/src/github.com/awslabs/k8s-cloudwatch-adapter/pkg/aws/util.go:29 +0x27e github.com/awslabs/k8s-cloudwatch-adapter/pkg/aws.NewCloudWatchManager(...) /go/src/github.com/awslabs/k8s-cloudwatch-adapter/pkg/aws/client.go:22 main.(*CloudWatchAdapter).makeCloudWatchManager(...) /go/src/github.com/awslabs/k8s-cloudwatch-adapter/cmd/adapter/adapter.go:28 main.main() /go/src/github.com/awslabs/k8s-cloudwatch-adapter/cmd/adapter/adapter.go:88 +0x256

**Comment by getsoubl** [comment]
Issue has been re

**Comment by getsoubl** [comment]
.

**Comment by getsoubl** [comment]
It is related with https://github.com/awslabs/k8s-cloudwatch-adapter/issues/86
